name: mpathic_env
channels:
  - wireland
dependencies:
  - python=3.6.9
  - numpy
  - pandas
  - Biopython=1.77
  - matplotlib
  - seaborn
  - scipy
  - pymc
  - ipython
  - scikit-learn
  - ipykernel
  - mpathic
  - mpmath
  - pip
  - pip:
    - -e .
    - watermark
    - logomaker
    - pytest  
